name: Go

on:
  release:
    types: [ "created" ]

jobs:

  build_and_upload_assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: Build Linux arm64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X csz.net/goForward/conf.version=${GITHUB_REF/refs\/tags\//}" -o goForward main.go

    - name: Zip Linux arm64
      run: |
        zip goForward_arm64.zip goForward

    - name: Build Linux amd64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X csz.net/goForward/conf.version=${GITHUB_REF/refs\/tags\//}" -o goForward main.go

    - name: Zip Linux amd64
      run: |
        zip goForward.zip goForward

    - name: Build Windows amd64
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-X csz.net/goForward/conf.version=${GITHUB_REF/refs\/tags\//}" -o goForward.exe main.go

    - name: Zip Windows amd64
      run: |
        zip goForward_win.zip goForward.exe

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          goForward.zip
          goForward_arm64.zip
          goForward_win.zip
